# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/asepulcri/Documents/BlackjackBot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/asepulcri/Documents/BlackjackBot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/asepulcri/Documents/BlackjackBot/CMakeFiles /home/asepulcri/Documents/BlackjackBot//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/asepulcri/Documents/BlackjackBot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BlackjackBot

# Build rule for target.
BlackjackBot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BlackjackBot
.PHONY : BlackjackBot

# fast build rule for target.
BlackjackBot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBot.dir/build.make CMakeFiles/BlackjackBot.dir/build
.PHONY : BlackjackBot/fast

#=============================================================================
# Target rules for targets named BlackjackBotApp

# Build rule for target.
BlackjackBotApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BlackjackBotApp
.PHONY : BlackjackBotApp

# fast build rule for target.
BlackjackBotApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/build
.PHONY : BlackjackBotApp/fast

source/card.o: source/card.cpp.o
.PHONY : source/card.o

# target to build an object file
source/card.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBot.dir/build.make CMakeFiles/BlackjackBot.dir/source/card.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/card.cpp.o
.PHONY : source/card.cpp.o

source/card.i: source/card.cpp.i
.PHONY : source/card.i

# target to preprocess a source file
source/card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBot.dir/build.make CMakeFiles/BlackjackBot.dir/source/card.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/card.cpp.i
.PHONY : source/card.cpp.i

source/card.s: source/card.cpp.s
.PHONY : source/card.s

# target to generate assembly for a file
source/card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBot.dir/build.make CMakeFiles/BlackjackBot.dir/source/card.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/card.cpp.s
.PHONY : source/card.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/player.o: source/player.cpp.o
.PHONY : source/player.o

# target to build an object file
source/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBot.dir/build.make CMakeFiles/BlackjackBot.dir/source/player.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/player.cpp.o
.PHONY : source/player.cpp.o

source/player.i: source/player.cpp.i
.PHONY : source/player.i

# target to preprocess a source file
source/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBot.dir/build.make CMakeFiles/BlackjackBot.dir/source/player.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/player.cpp.i
.PHONY : source/player.cpp.i

source/player.s: source/player.cpp.s
.PHONY : source/player.s

# target to generate assembly for a file
source/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBot.dir/build.make CMakeFiles/BlackjackBot.dir/source/player.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/player.cpp.s
.PHONY : source/player.cpp.s

source/shoe.o: source/shoe.cpp.o
.PHONY : source/shoe.o

# target to build an object file
source/shoe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBot.dir/build.make CMakeFiles/BlackjackBot.dir/source/shoe.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/shoe.cpp.o
.PHONY : source/shoe.cpp.o

source/shoe.i: source/shoe.cpp.i
.PHONY : source/shoe.i

# target to preprocess a source file
source/shoe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBot.dir/build.make CMakeFiles/BlackjackBot.dir/source/shoe.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/shoe.cpp.i
.PHONY : source/shoe.cpp.i

source/shoe.s: source/shoe.cpp.s
.PHONY : source/shoe.s

# target to generate assembly for a file
source/shoe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBot.dir/build.make CMakeFiles/BlackjackBot.dir/source/shoe.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackBotApp.dir/build.make CMakeFiles/BlackjackBotApp.dir/source/shoe.cpp.s
.PHONY : source/shoe.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BlackjackBot"
	@echo "... BlackjackBotApp"
	@echo "... source/card.o"
	@echo "... source/card.i"
	@echo "... source/card.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/player.o"
	@echo "... source/player.i"
	@echo "... source/player.s"
	@echo "... source/shoe.o"
	@echo "... source/shoe.i"
	@echo "... source/shoe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

